<?php

return [
    'ar' => [
        'name' => 'الاسم',
        'user_name' => 'إسم المستخدم',
        'username' => 'اسم المُستخدم',
        'email' => 'البريد الالكتروني',
        'pin_code' => 'كود التفعيل',
        'first_name' => 'الاسم الأول',
        'last_name' => 'اسم العائلة',
        'password' => 'الرقم السرى',
        'old-password' => 'الرقم السرى الحالى',
        'password_confirmation' => 'تأكيد الرقم السر',
        'city' => ' حقل المدينة',
        'country' => 'حقل الدولة',
        'address' => 'عنوان السكن',
        'phone' => 'الهاتف',
        'mobile' => 'الجوال',
        'age' => 'العمر',
        'sex' => 'الجنس',
        'gender' => 'النوع',
        'title' => 'العنوان',
        'title.ar' => ' العنوان باللغه العربيه',
        'title.en' => ' العنوان باللغه الانجليزيه',
        'desc.ar' => ' الوصف باللغه العربيه',
        'desc.en' => ' الوصف باللغه الانجليزيه',
        'short_desc.ar' => ' الوصف القسير باللغه العربيه',
        'short_desc.en' => ' الوصف القسير باللغه الانجليزيه',
        'content' => 'المُحتوى',
        'description' => 'الوصف',
        'excerpt' => 'المُلخص',
        'date' => 'التاريخ',
        'time' => 'الوقت',
        'city_id' => ' المدينة',
        'photo' => '  الصورة',
        'degree' => ' درجه',
        'success_degree' => 'درجه النجاح',
        'description.ar' => ' الوصف باللغه العربيه',
        'description.en' => ' الوصف باللغه الانجليزيه',
        'question.ar' => ' السؤال باللغه العربيه',
        'question.en' => ' السؤال باللغه الانجليزيه',
        'category_id'    => 'القسم',
        'image'    => 'الصوره',
        'exam_id'                       => 'الامتحان',
        'extra_attributes.price'        =>'السعر',
        'extra_attributes.gender'       =>'النوع',
        'extra_attributes.start_date'       => 'تاريخ البدايه',
        'extra_attributes.end_date'         => 'تاريخ النهايه',
        'extra_attributes.duration'         => 'المده',
    ],

];
